### ISSUE TITLE
homomcl can't be used

### ISSUE THREAD

**Issue by KseniaJuravel** [willpett/homomcl#1]
Hello Walker

Thank you for this git rep for your tool!

I analyzed Arthropod data set and created an id-length file and BLASTP tab delimited. 
Unfortunately the homomc starts to run (CPUs and memory uses) but does not create any output and stops after 4 min. 
There is no example of the data here,  so I do not know what is wrong. 

I am using this command: $ homomcl awk_id_length 1e-5 BLASTP_all 

The files are:
awk_id_length - file of id's as they appear in the -outfmt 6 BLAST result 'Query Seq-id' column and query length column. 
                I used the command 'awk'! Seen [$ 0] ++ 'to remove duplicates.

BLASTP_all vs all output file (with cutoff 1.0e-5), without any changes. 

Can you please help me and indicate what may be the problem and what are the correct steps? 

Thank you,
Ksenia

**Comment by milliescient** [comment]
Hi Ksenia,

Very sorry about that. You're right, I discovered a small mistake in the code that I accidentally left in place from some debugging. Please let me know if it works for you now.

**Comment by KseniaJuravel** [comment]
Hi, thank you very much for the answer!!!

Now it is running, but...
My BLASTP file is 11G, the homomcl created a 1.2G output file and raised the following error:
'Segmentation fault'. 
I think it as nothing to do with the computer RAM, since I tried it with RAM setting of 128G and 500G.
May be still something in the code?

Many Thanks again!  :)

**Comment by milliescient** [comment]
Hm, not sure what the issue is. I commented out an unnecessary part of the code, which might fix your problem. If it doesn't, could you please attach a sample of your input files? It could be that the Segmentation fault is occurring at the end of the program and does not impact the output at all.

**Comment by KseniaJuravel** [comment]
It helped and this time the run ended successfully. Thank you very much!!!!
